version: '{build}'
image: Visual Studio 2017

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  OPENSSL_ROOT_DIR: c:\grimm-libs\openssl
  QT5_ROOT_DIR: c:\grimm-libs\qt5-static-win
  QML_IMPORT_PATH: c:\grimm-libs\qt5-static-win\qml
  BUILD_SERVER:
    secure: l9RqB2YbSnNIKZqTwnd67BHAXvbjmpj9zcf+YQPi9zfzsVeSysaoLD7gy4gSMjWurk2JVHjRpviw4bBxUbu2sA==
  BUILD_CONFIG: RelWithDebInfo
  PATH: c:\grimm-libs\qt5-static-win\bin;$(PATH)

before_build:
  - cmd: git clone --depth=1 https://github.com/freenetcoder/libs.git c:/grimm-libs
  - cmd: git clone --depth=1 https://github.com/nesbox/qt5-static-win.git c:/grimm-libs/qt5-static-win
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=%BUILD_CONFIG% -DGRIMM_LINK_TYPE=Static -DBRANCH_NAME=%APPVEYOR_REPO_BRANCH% -DGRIMM_BUILD_JNI=On.

test_script:
  - cmd: ctest -C %BUILD_CONFIG% --verbose

build_script:
  - cmake --build . --parallel --config %BUILD_CONFIG%

after_build:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- ps: $env:GRIMM_TARGET_SUFFIX='-masternet'
- ps: $env:GRIMM_DISPLAY_SUFFIX='Masternet'
- ps: $env:GRIMM_DISPLAY_SUFFIX2='-Masternet'
- ps: $env:GRIMM_DISPLAY_SUFFIX3=' Masternet'
- cmd: >-
    cpack --verbose -G NSIS -C %BUILD_CONFIG%

    set /p GRIMM_VERSION=<grimm_version.gen

    echo GRIMM_VERSION = %GRIMM_VERSION%

    del grimm_version.gen

    7z a c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-node%GRIMM_TARGET_SUFFIX%.exe c:/projects/grimm/grimm/grimm-node.cfg

    7z a c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:/projects/grimm/wallet/%BUILD_CONFIG%/grimm-wallet%GRIMM_TARGET_SUFFIX%.exe c:/projects/grimm/wallet/grimm-wallet.cfg

    7z a c:/projects/grimm/grimm/%BUILD_CONFIG%/wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:/projects/grimm/wallet/%BUILD_CONFIG%/wallet-api%GRIMM_TARGET_SUFFIX%.exe c:/projects/grimm/wallet/wallet-api.cfg

    7z a c:/projects/grimm/grimm/%BUILD_CONFIG%/explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:/projects/grimm/explorer/%BUILD_CONFIG%/explorer-node%GRIMM_TARGET_SUFFIX%.exe c:/projects/grimm/explorer/explorer-node.cfg

    mkdir pdb

    7z a c:/projects/grimm/grimm/grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip "c:/projects/grimm/ui/%BUILD_CONFIG%/Grimm Wallet%GRIMM_DISPLAY_SUFFIX3%.pdb" "c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-node%GRIMM_TARGET_SUFFIX%.pdb" "c:/projects/grimm/wallet/%BUILD_CONFIG%/grimm-wallet%GRIMM_TARGET_SUFFIX%.pdb"

    copy c:\projects\grimm\grimm\%BUILD_CONFIG%\grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:\projects\grimm\grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip

    copy c:\projects\grimm\grimm\%BUILD_CONFIG%\grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:\projects\grimm\grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip

    copy c:\projects\grimm\grimm\%BUILD_CONFIG%\wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:\projects\grimm\wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip

    copy c:\projects\grimm\grimm\%BUILD_CONFIG%\explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:\projects\grimm\explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip

    copy c:\projects\grimm\grimm\grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip c:\projects\grimm\pdb\grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip

    copy c:\projects\grimm\GrimmWallet%GRIMM_DISPLAY_SUFFIX%-%GRIMM_VERSION%-win64.exe c:\projects\grimm\Grimm-Wallet%GRIMM_DISPLAY_SUFFIX2%-%GRIMM_VERSION%.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip" "%BUILDS_SERVER_PATH%/grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/grimm/%BUILD_CONFIG%/grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip" "%BUILDS_SERVER_PATH%/grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/grimm/%BUILD_CONFIG%/wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip" "%BUILDS_SERVER_PATH%/wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/grimm/%BUILD_CONFIG%/explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip" "%BUILDS_SERVER_PATH%/explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/GrimmWallet%GRIMM_DISPLAY_SUFFIX%-%GRIMM_VERSION%-win64.exe" "%BUILDS_SERVER_PATH%/Grimm-Wallet%GRIMM_DISPLAY_SUFFIX2%-%GRIMM_VERSION%.exe"

    curl --retry 3 --ftp-create-dirs -T "c:/projects/grimm/grimm/grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip" "%BUILDS_SERVER_PATH%/pdb/grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip"

artifacts:
  - path: grimm-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip
    name: GrimmNode

  - path: grimm-wallet-cli%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip
    name: GrimmWalletCli

  - path: wallet-api%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip
    name: GrimmWalletApi

  - path: explorer-node%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip
    name: GrimmNodeExplorer

  - path: pdb/grimm-pdb%GRIMM_TARGET_SUFFIX%-%GRIMM_VERSION%.zip
    name: GrimmPdb

  - path: Grimm-Wallet%GRIMM_DISPLAY_SUFFIX2%-%GRIMM_VERSION%.exe
    name: GrimmWallet

deploy:
  provider: S3
  access_key_id:
    secure: J8+/d4TSbhxiaFlDQopFzKbfLPvUy1rMUJlAgnfbBNE=
  secret_access_key:
    secure: sqF9zdsuUm/k9QzY46s250MZJamHjKrwBCAPbinBA/iOJlgLsHC7lq1F5pTr/B+U
  bucket: builds.grimmw.com
  region: us-west-2
  unzip: false
  set_public: true
  folder: "%APPVEYOR_REPO_BRANCH%/%DATE%/Release/win/"
  artifact: GrimmPdb, GrimmWalletApi, GrimmNodeExplorer, GrimmWalletCli, GrimmNode, GrimmWallet

notifications:
  - provider: Email
    to:
      - big.romanov@gmail.com
